[package]
name = "lookup-tables"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
float_eq = "1.0.1"
nalgebra = "0.33.2"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
